<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Quiz;

class QuizSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Module 1: Pengenalan Pemrograman Web - Multiple Choice
        $webProgrammingMC = [
            [
                'module_id' => 1,
                'question' => 'Apa kepanjangan dari HTML?',
                'option_a' => 'HyperText Markup Language',
                'option_b' => 'HyperText Making Language',
                'option_c' => 'HyperText Management Language',
                'option_d' => 'HyperText Modification Language',
                'correct_answer' => 'a',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 1,
                'question' => 'Tag HTML mana yang digunakan untuk membuat heading terbesar?',
                'option_a' => '<h6>',
                'option_b' => '<h1>',
                'option_c' => '<header>',
                'option_d' => '<title>',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 1,
                'question' => 'CSS singkatan dari?',
                'option_a' => 'Computer Style Sheets',
                'option_b' => 'Creative Style Sheets',
                'option_c' => 'Cascading Style Sheets',
                'option_d' => 'Colorful Style Sheets',
                'correct_answer' => 'c',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 1,
                'question' => 'JavaScript adalah bahasa pemrograman yang berjalan di?',
                'option_a' => 'Server saja',
                'option_b' => 'Client saja',
                'option_c' => 'Client dan Server',
                'option_d' => 'Database',
                'correct_answer' => 'c',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 1,
                'question' => 'Atribut HTML mana yang digunakan untuk styling inline?',
                'option_a' => 'class',
                'option_b' => 'id',
                'option_c' => 'style',
                'option_d' => 'css',
                'correct_answer' => 'c',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 1,
                'question' => 'Method HTTP mana yang digunakan untuk mengirim data form?',
                'option_a' => 'GET',
                'option_b' => 'POST',
                'option_c' => 'PUT',
                'option_d' => 'DELETE',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 1,
                'question' => 'Selector CSS mana yang memiliki prioritas tertinggi?',
                'option_a' => 'Element selector',
                'option_b' => 'Class selector',
                'option_c' => 'ID selector',
                'option_d' => 'Inline style',
                'correct_answer' => 'd',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 1,
                'question' => 'Tag HTML mana yang digunakan untuk menampilkan gambar?',
                'option_a' => '<image>',
                'option_b' => '<img>',
                'option_c' => '<picture>',
                'option_d' => '<photo>',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 1,
                'question' => 'Event JavaScript mana yang terjadi saat halaman selesai dimuat?',
                'option_a' => 'onclick',
                'option_b' => 'onload',
                'option_c' => 'onchange',
                'option_d' => 'onsubmit',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 1,
                'question' => 'Property CSS mana yang digunakan untuk mengatur jarak antar elemen?',
                'option_a' => 'padding',
                'option_b' => 'margin',
                'option_c' => 'border',
                'option_d' => 'spacing',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
        ];

        // Module 1: Pengenalan Pemrograman Web - Essay
        $webProgrammingEssay = [
            [
                'module_id' => 1,
                'question' => 'Jelaskan perbedaan antara HTML, CSS, dan JavaScript dalam pengembangan web!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'HTML adalah bahasa markup untuk struktur konten, CSS untuk styling dan tampilan, JavaScript untuk interaktivitas dan logika program.',
            ],
            [
                'module_id' => 1,
                'question' => 'Apa yang dimaksud dengan responsive web design dan mengapa penting?',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Responsive web design adalah pendekatan desain yang membuat website dapat menyesuaikan tampilan dengan berbagai ukuran layar dan perangkat.',
            ],
            [
                'module_id' => 1,
                'question' => 'Sebutkan dan jelaskan 5 tag HTML semantik!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Header, nav, main, article, section, aside, footer - tag yang memberikan makna struktural pada konten.',
            ],
            [
                'module_id' => 1,
                'question' => 'Bagaimana cara kerja CSS Box Model?',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'CSS Box Model terdiri dari content, padding, border, dan margin yang menentukan ukuran dan ruang elemen.',
            ],
            [
                'module_id' => 1,
                'question' => 'Jelaskan perbedaan antara var, let, dan const dalam JavaScript!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'var: function scope, let: block scope dapat diubah, const: block scope tidak dapat diubah nilainya.',
            ],
            [
                'module_id' => 1,
                'question' => 'Apa itu DOM dan bagaimana JavaScript berinteraksi dengannya?',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'DOM adalah representasi struktur dokumen HTML sebagai objek yang dapat dimanipulasi oleh JavaScript.',
            ],
            [
                'module_id' => 1,
                'question' => 'Jelaskan konsep event handling dalam JavaScript!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Event handling adalah proses menangani aksi user seperti click, hover, submit melalui event listener.',
            ],
            [
                'module_id' => 1,
                'question' => 'Sebutkan keuntungan menggunakan CSS Framework seperti Bootstrap!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Pengembangan lebih cepat, konsistensi desain, responsive grid system, komponen siap pakai.',
            ],
            [
                'module_id' => 1,
                'question' => 'Apa itu AJAX dan bagaimana cara kerjanya?',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'AJAX adalah teknik untuk melakukan request HTTP asynchronous tanpa me-refresh seluruh halaman.',
            ],
            [
                'module_id' => 1,
                'question' => 'Jelaskan perbedaan antara client-side dan server-side programming!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Client-side berjalan di browser user, server-side berjalan di server untuk memproses data dan logic.',
            ],
        ];

        // Module 2: Database dan MySQL - Multiple Choice
        $databaseMC = [
            [
                'module_id' => 2,
                'question' => 'Apa kepanjangan dari RDBMS?',
                'option_a' => 'Relational Database Management System',
                'option_b' => 'Real Database Management System',
                'option_c' => 'Remote Database Management System',
                'option_d' => 'Reliable Database Management System',
                'correct_answer' => 'a',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 2,
                'question' => 'SQL command mana yang digunakan untuk mengambil data dari database?',
                'option_a' => 'GET',
                'option_b' => 'SELECT',
                'option_c' => 'FETCH',
                'option_d' => 'RETRIEVE',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 2,
                'question' => 'Primary Key dalam database berfungsi untuk?',
                'option_a' => 'Mengurutkan data',
                'option_b' => 'Mengidentifikasi record secara unik',
                'option_c' => 'Menyimpan password',
                'option_d' => 'Mengenkripsi data',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 2,
                'question' => 'Normalisasi database bertujuan untuk?',
                'option_a' => 'Mempercepat query',
                'option_b' => 'Mengurangi redundansi data',
                'option_c' => 'Mengamankan data',
                'option_d' => 'Membackup data',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 2,
                'question' => 'JOIN dalam SQL digunakan untuk?',
                'option_a' => 'Menggabungkan tabel',
                'option_b' => 'Menghapus data',
                'option_c' => 'Mengupdate data',
                'option_d' => 'Membuat tabel',
                'correct_answer' => 'a',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 2,
                'question' => 'Tipe data MySQL mana yang cocok untuk menyimpan tanggal?',
                'option_a' => 'VARCHAR',
                'option_b' => 'INT',
                'option_c' => 'DATE',
                'option_d' => 'TEXT',
                'correct_answer' => 'c',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 2,
                'question' => 'Command SQL mana yang digunakan untuk menambah data baru?',
                'option_a' => 'ADD',
                'option_b' => 'INSERT',
                'option_c' => 'CREATE',
                'option_d' => 'NEW',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 2,
                'question' => 'Index dalam database berfungsi untuk?',
                'option_a' => 'Mengamankan data',
                'option_b' => 'Mempercepat pencarian',
                'option_c' => 'Membackup data',
                'option_d' => 'Mengkompresi data',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 2,
                'question' => 'Foreign Key digunakan untuk?',
                'option_a' => 'Mengunci tabel',
                'option_b' => 'Membuat relasi antar tabel',
                'option_c' => 'Mengenkripsi data',
                'option_d' => 'Menghapus data otomatis',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 2,
                'question' => 'Clause SQL mana yang digunakan untuk filtering data?',
                'option_a' => 'ORDER BY',
                'option_b' => 'GROUP BY',
                'option_c' => 'WHERE',
                'option_d' => 'HAVING',
                'correct_answer' => 'c',
                'type' => 'multiple_choice',
            ],
        ];

        // Module 2: Database dan MySQL - Essay
        $databaseEssay = [
            [
                'module_id' => 2,
                'question' => 'Jelaskan perbedaan antara DDL, DML, dan DCL dalam SQL!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'DDL: Data Definition Language (CREATE, ALTER, DROP), DML: Data Manipulation Language (SELECT, INSERT, UPDATE, DELETE), DCL: Data Control Language (GRANT, REVOKE).',
            ],
            [
                'module_id' => 2,
                'question' => 'Apa itu ACID properties dalam database dan jelaskan masing-masing!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Atomicity: transaksi all or nothing, Consistency: data tetap konsisten, Isolation: transaksi tidak saling mengganggu, Durability: perubahan permanen tersimpan.',
            ],
            [
                'module_id' => 2,
                'question' => 'Sebutkan dan jelaskan macam-macam JOIN dalam SQL!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'INNER JOIN: data yang match di kedua tabel, LEFT JOIN: semua data dari tabel kiri, RIGHT JOIN: semua data dari tabel kanan, FULL OUTER JOIN: semua data dari kedua tabel.',
            ],
            [
                'module_id' => 2,
                'question' => 'Jelaskan konsep normalisasi database hingga 3NF!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => '1NF: tidak ada repeating groups, 2NF: tidak ada partial dependency, 3NF: tidak ada transitive dependency.',
            ],
            [
                'module_id' => 2,
                'question' => 'Apa itu stored procedure dan apa keuntungannya?',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Stored procedure adalah kumpulan SQL statements yang disimpan di database. Keuntungan: performance lebih baik, security, reusability.',
            ],
            [
                'module_id' => 2,
                'question' => 'Jelaskan perbedaan antara UNION dan UNION ALL!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'UNION menghilangkan duplikasi dan mengurutkan hasil, UNION ALL menampilkan semua data termasuk duplikat tanpa pengurutan.',
            ],
            [
                'module_id' => 2,
                'question' => 'Apa itu database transaction dan bagaimana cara kerjanya?',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Transaction adalah unit kerja yang terdiri dari satu atau lebih operasi database yang harus berhasil semua atau gagal semua (COMMIT/ROLLBACK).',
            ],
            [
                'module_id' => 2,
                'question' => 'Sebutkan macam-macam index dalam MySQL dan kegunaannya!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'PRIMARY: untuk primary key, UNIQUE: untuk unique constraint, INDEX/KEY: untuk mempercepat pencarian, FULLTEXT: untuk pencarian teks.',
            ],
            [
                'module_id' => 2,
                'question' => 'Jelaskan konsep backup dan recovery dalam database!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Backup adalah proses menyimpan copy data untuk recovery. Jenis: full backup, incremental, differential. Recovery mengembalikan data dari backup.',
            ],
            [
                'module_id' => 2,
                'question' => 'Apa itu database optimization dan teknik apa saja yang dapat dilakukan?',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Optimisasi untuk meningkatkan performance: indexing, query optimization, normalisasi, partitioning, caching.',
            ],
        ];

        // Module 3: Framework Laravel - Multiple Choice
        $laravelMC = [
            [
                'module_id' => 3,
                'question' => 'Laravel menggunakan pola arsitektur apa?',
                'option_a' => 'MVP',
                'option_b' => 'MVC',
                'option_c' => 'MVVM',
                'option_d' => 'MVA',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 3,
                'question' => 'Command artisan untuk membuat controller adalah?',
                'option_a' => 'php artisan create:controller',
                'option_b' => 'php artisan make:controller',
                'option_c' => 'php artisan new:controller',
                'option_d' => 'php artisan gen:controller',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 3,
                'question' => 'Eloquent ORM dalam Laravel digunakan untuk?',
                'option_a' => 'Routing',
                'option_b' => 'Authentication',
                'option_c' => 'Database interaction',
                'option_d' => 'View rendering',
                'correct_answer' => 'c',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 3,
                'question' => 'File konfigurasi utama Laravel terletak di folder?',
                'option_a' => 'app',
                'option_b' => 'config',
                'option_c' => 'resources',
                'option_d' => 'storage',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 3,
                'question' => 'Middleware dalam Laravel berfungsi untuk?',
                'option_a' => 'Database migration',
                'option_b' => 'HTTP request filtering',
                'option_c' => 'View compilation',
                'option_d' => 'Route caching',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 3,
                'question' => 'Blade adalah template engine Laravel yang menggunakan ekstensi file?',
                'option_a' => '.php',
                'option_b' => '.html',
                'option_c' => '.blade.php',
                'option_d' => '.tpl',
                'correct_answer' => 'c',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 3,
                'question' => 'Command untuk menjalankan migration adalah?',
                'option_a' => 'php artisan migrate',
                'option_b' => 'php artisan db:migrate',
                'option_c' => 'php artisan migration:run',
                'option_d' => 'php artisan run:migrate',
                'correct_answer' => 'a',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 3,
                'question' => 'Service Container dalam Laravel digunakan untuk?',
                'option_a' => 'Database connection',
                'option_b' => 'Dependency injection',
                'option_c' => 'Route handling',
                'option_d' => 'File storage',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 3,
                'question' => 'Facade dalam Laravel adalah?',
                'option_a' => 'Design pattern',
                'option_b' => 'Static interface to service container',
                'option_c' => 'Database model',
                'option_d' => 'HTTP response',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 3,
                'question' => 'Validation dalam Laravel biasanya dilakukan di?',
                'option_a' => 'Model',
                'option_b' => 'View',
                'option_c' => 'Controller atau Form Request',
                'option_d' => 'Route',
                'correct_answer' => 'c',
                'type' => 'multiple_choice',
            ],
        ];

        // Module 3: Framework Laravel - Essay
        $laravelEssay = [
            [
                'module_id' => 3,
                'question' => 'Jelaskan konsep MVC dalam Laravel dan bagaimana alur kerjanya!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Model: mengelola data dan business logic, View: menampilkan data ke user, Controller: menghubungkan Model dan View, menangani request dan response.',
            ],
            [
                'module_id' => 3,
                'question' => 'Apa itu Eloquent ORM dan apa keuntungannya dibanding raw SQL?',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Eloquent adalah Active Record ORM yang memungkinkan interaksi database menggunakan PHP object. Keuntungan: syntax yang mudah, relationship handling, mass assignment protection.',
            ],
            [
                'module_id' => 3,
                'question' => 'Jelaskan lifecycle request Laravel dari route hingga response!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'HTTP Request → Route → Middleware → Controller → Model (jika diperlukan) → View → HTTP Response.',
            ],
            [
                'module_id' => 3,
                'question' => 'Apa itu Service Provider dan bagaimana cara kerjanya dalam Laravel?',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Service Provider adalah tempat untuk binding service ke service container, bootstrapping aplikasi. Memiliki method register() dan boot().',
            ],
            [
                'module_id' => 3,
                'question' => 'Sebutkan dan jelaskan macam-macam relationship dalam Eloquent!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'One To One (hasOne/belongsTo), One To Many (hasMany/belongsTo), Many To Many (belongsToMany), Has One Through, Has Many Through, Polymorphic relations.',
            ],
            [
                'module_id' => 3,
                'question' => 'Jelaskan konsep middleware dan berikan contoh penggunaannya!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Middleware adalah filter HTTP request sebelum mencapai controller. Contoh: authentication, CORS, rate limiting, logging.',
            ],
            [
                'module_id' => 3,
                'question' => 'Apa itu Laravel Artisan dan sebutkan 5 command yang sering digunakan!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Artisan adalah command-line interface Laravel. Command: make:controller, make:model, migrate, serve, tinker, make:middleware, route:list.',
            ],
            [
                'module_id' => 3,
                'question' => 'Jelaskan perbedaan antara Route Model Binding dan Manual Route!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Route Model Binding otomatis resolve model dari parameter route, Manual Route memerlukan query manual untuk mendapatkan model.',
            ],
            [
                'module_id' => 3,
                'question' => 'Apa itu Laravel Blade dan apa saja fitur-fiturnya?',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Blade adalah template engine Laravel dengan fitur: template inheritance, sections, includes, loops, conditionals, components, slots.',
            ],
            [
                'module_id' => 3,
                'question' => 'Jelaskan konsep dependency injection dalam Laravel!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Dependency injection adalah teknik memberikan dependencies ke class dari luar, bukan membuat di dalam class. Laravel menggunakan Service Container untuk auto-resolution.',
            ],
        ];

        // Module 4: React Native - Multiple Choice
        $reactNativeMC = [
            [
                'module_id' => 4,
                'question' => 'React Native dikembangkan oleh?',
                'option_a' => 'Google',
                'option_b' => 'Facebook',
                'option_c' => 'Microsoft',
                'option_d' => 'Apple',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 4,
                'question' => 'Language utama yang digunakan React Native adalah?',
                'option_a' => 'Java',
                'option_b' => 'Swift',
                'option_c' => 'JavaScript',
                'option_d' => 'Kotlin',
                'correct_answer' => 'c',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 4,
                'question' => 'Component untuk menampilkan teks dalam React Native adalah?',
                'option_a' => '<div>',
                'option_b' => '<span>',
                'option_c' => '<Text>',
                'option_d' => '<Label>',
                'correct_answer' => 'c',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 4,
                'question' => 'Hook React yang digunakan untuk state management adalah?',
                'option_a' => 'useEffect',
                'option_b' => 'useState',
                'option_c' => 'useContext',
                'option_d' => 'useCallback',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 4,
                'question' => 'Styling dalam React Native menggunakan?',
                'option_a' => 'CSS',
                'option_b' => 'SCSS',
                'option_c' => 'StyleSheet',
                'option_d' => 'Styled Components',
                'correct_answer' => 'c',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 4,
                'question' => 'Navigation library yang populer untuk React Native adalah?',
                'option_a' => 'React Router',
                'option_b' => 'React Navigation',
                'option_c' => 'Native Navigation',
                'option_d' => 'React Native Router',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 4,
                'question' => 'Component untuk input teks adalah?',
                'option_a' => '<Input>',
                'option_b' => '<TextInput>',
                'option_c' => '<TextField>',
                'option_d' => '<EditText>',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 4,
                'question' => 'Platform mana yang didukung React Native?',
                'option_a' => 'iOS saja',
                'option_b' => 'Android saja',
                'option_c' => 'iOS dan Android',
                'option_d' => 'Web saja',
                'correct_answer' => 'c',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 4,
                'question' => 'Command untuk membuat project React Native baru adalah?',
                'option_a' => 'create-react-native-app',
                'option_b' => 'react-native init',
                'option_c' => 'npx react-native init',
                'option_d' => 'react-native create',
                'correct_answer' => 'c',
                'type' => 'multiple_choice',
            ],
            [
                'module_id' => 4,
                'question' => 'Flexbox adalah default layout system di React Native untuk?',
                'option_a' => 'Styling color',
                'option_b' => 'Arrangement components',
                'option_c' => 'Navigation',
                'option_d' => 'State management',
                'correct_answer' => 'b',
                'type' => 'multiple_choice',
            ],
        ];

        // Module 4: React Native - Essay
        $reactNativeEssay = [
            [
                'module_id' => 4,
                'question' => 'Jelaskan perbedaan React Native dengan Native Development (Swift/Java)!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'React Native: cross-platform, JavaScript, faster development, shared codebase. Native: platform-specific, better performance, full access to native APIs.',
            ],
            [
                'module_id' => 4,
                'question' => 'Apa itu JSX dan bagaimana penggunaannya dalam React Native?',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'JSX adalah syntax extension JavaScript yang memungkinkan menulis UI components seperti HTML dalam JavaScript, dikompilasi menjadi JavaScript calls.',
            ],
            [
                'module_id' => 4,
                'question' => 'Jelaskan lifecycle methods dalam React Native component!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'componentDidMount: setelah component mount, componentDidUpdate: setelah update, componentWillUnmount: sebelum unmount, atau menggunakan useEffect hook.',
            ],
            [
                'module_id' => 4,
                'question' => 'Apa itu Props dan State dalam React Native? Jelaskan perbedaannya!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Props: data yang diterima dari parent component (immutable), State: data internal component yang dapat berubah (mutable).',
            ],
            [
                'module_id' => 4,
                'question' => 'Sebutkan dan jelaskan core components React Native yang sering digunakan!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'View: container component, Text: menampilkan teks, Image: menampilkan gambar, ScrollView: scrollable content, FlatList: efficient list, TouchableOpacity: touchable area.',
            ],
            [
                'module_id' => 4,
                'question' => 'Bagaimana cara handling navigation dalam React Native?',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Menggunakan React Navigation library dengan Stack Navigator, Tab Navigator, Drawer Navigator untuk berpindah antar screen.',
            ],
            [
                'module_id' => 4,
                'question' => 'Jelaskan konsep Flexbox dalam React Native styling!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Flexbox mengatur layout dengan flex direction, justify content (main axis), align items (cross axis), flex wrap untuk responsive design.',
            ],
            [
                'module_id' => 4,
                'question' => 'Apa itu AsyncStorage dan bagaimana penggunaannya?',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'AsyncStorage adalah local storage untuk menyimpan data secara persistent, digunakan untuk cache, user preferences, token authentication.',
            ],
            [
                'module_id' => 4,
                'question' => 'Bagaimana cara melakukan HTTP request dalam React Native?',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Menggunakan fetch API atau library seperti Axios, biasanya dalam useEffect hook atau event handler untuk GET, POST, PUT, DELETE request.',
            ],
            [
                'module_id' => 4,
                'question' => 'Jelaskan proses build dan deployment React Native app!',
                'option_a' => null,
                'option_b' => null,
                'option_c' => null,
                'option_d' => null,
                'correct_answer' => null,
                'type' => 'essay',
                'answer_key' => 'Build: react-native run-android/ios untuk development, generate signed APK/IPA untuk production. Deploy: Google Play Store (Android), App Store (iOS) dengan review process.',
            ],
        ];

        // Insert all quiz data
        foreach (array_merge($webProgrammingMC, $webProgrammingEssay, $databaseMC, $databaseEssay, $laravelMC, $laravelEssay, $reactNativeMC, $reactNativeEssay) as $quiz) {
            Quiz::create($quiz);
        }
    }
}
